# Uncomment this line to define a global platform for your project
platform :ios, '10.0'

target 'PAMDemo' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'PAM', :path => '../'

  target 'PAMDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PAMDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
